packages:
  - apps/*
  - packages/*
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

catalog:
  eslint: ^9.25.1
  prettier: ^3.5.3
  typescript: ^5.8.3
  "@types/node": ^22.15.3

catalogs:
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": "^19.1.0"
    "@types/react-dom": "^19.1.0"